import ButtonLink from "./ButtonLink";

export default {
  title: "UI/ButtonLink",
  component: ButtonLink,
  parameters: {
    layout: "centered",
    docs: {
      description: {
        story: `ButtonLink is a component that renders either a Link or a Button, depending on whether it receives a href or a onClick prop.

### TODO
- [ ] Add accessibility features (e.g. focus styles)
- [ ] Test with long labels
- [ ] "color" should be renamed "style" and allow outline and fill for both primary and secondary colors.
        `,
      },
    },
  },
  tags: ["autodocs"],
  argTypes: {
    children: { table: { disable: true } }, // Remove autogenerated Children prop from Doc
  },
};

export const Default = {
  args: {
    href: "/",
    children: "Button",
  },
};
